AdvisorySG/mentorship-page

src/components/profile-card.css, src/components/profile-card.jsx
Fixes #9 
Here's what it looks like with the committed changes:
Before hover:
After hover:
Feel free to suggest changes for color etc!
=> Style button and add opacity on hover

src/App.css, src/components/profile-card.css, src/components/profile-card.jsx
This PR relates to https://github.com/AdvisorySG/mentorship-page/issues/13 and contains a couple of adjustments to make the grid more responsive.
=> ProfileCards: Desktop flexbox adjustments

src/components/profile-modal.css
=> Ensure that modal’s close button is above content.

package-lock.json, package.json, src/components/profile-card.jsx
This PR implements lazy loading with [react-lazyload](https://github.com/twobin/react-lazyload) and relates to https://github.com/AdvisorySG/mentorship-page/issues/12.
=> ProfileCard: Implement lazy loading of images

package-lock.json, package.json, src/components/profile-card.jsx
Reverts AdvisorySG/mentorship-page#18
=> Revert "ProfileCard: Implement lazy loading of images"

src/App.css, src/App.js, src/components/header.css, src/components/header.jsx, src/components/profile-card.css, src/components/profile-card.jsx, src/components/profile-modal.css, src/components/profile-modal.jsx
The current `className`s used across the app don't have any hierarchical structure, and it's quite easy to end up with namespace conflicts over classes (as I just faced in one of my recent changes). This PR proposes an uniform structure for `className`s.
=> Housekeeping: Rename className to prevent namespace conflicts

src/App.css, src/App.js, src/components/header.css, src/components/header.jsx, src/components/profile-card.css, src/components/profile-card.jsx, src/components/profile-modal.css, src/components/profile-modal.jsx
Reverts AdvisorySG/mentorship-page#23
=> Revert "Housekeeping: Rename className to prevent namespace conflicts"

src/App.js, src/components/header.jsx, src/components/profile-card.jsx, src/components/profile-modal.jsx, src/index.js, src/mentorsData.js
Reverts AdvisorySG/mentorship-page#19
=> Revert "Housekeeping: Reorganise imports and exports"

src/components/profile-modal.jsx, src/index.js
It can also be closed using the `Esc` key.
Note: I sent this PR to the `modal` branch, so you might need to merge this into `modal` before merging #31 into `master`.
Ref. #16.
=> Allow modal to be closed upon clicking outside.

public/index.html
=> Fix title and description

package-lock.json, package.json, src/App.js, src/components/profile-modal.css, src/components/profile-modal.jsx, src/index.js
Fixes #20. Partially addresses #21 (modal now stays in absolute position) and #22 (grey overlay now renders over rest of site when modal is active).
Outstanding modal-related issues: 
Viewed at 100% zoom:
Viewed at 67% zoom:
=> Use react-modal

src/App.css, src/components/profile-card.css
| **Before** | **After**|
|:---:|:---:|
| ![IMG_20200416_151521](https://user-images.githubusercontent.com/813865/79428003-2229c080-7ff8-11ea-8c04-3a68c16a342f.jpg) | ![IMG_20200416_151506](https://user-images.githubusercontent.com/813865/79427991-1e963980-7ff8-11ea-943c-0981b0c6d9e8.jpg) |
Ref. #13.
=> Maximize card display on smaller viewports.

src/App.js, src/mentorsData.js
=> Mentors: Remove references to mentor.id

src/components/profile-card.css
Fixes https://github.com/AdvisorySG/mentorship-page/issues/45
=> ProfileCard: Restrict cards to fixed width based on viewport

src/components/header.jsx
Resolves https://github.com/AdvisorySG/mentorship-page/issues/42
=> Header: Have TypeForm link open in new tab

src/components/profile-card.css
=> Ensure “Read More” buttons are at the bottom of the card.

package.json, src/App.js, src/components/profile-modal.css, src/components/profile-modal.jsx
- Add body scroll locking
- Simple transitions for the modal
=> Modal improvements

src/components/profile-modal.jsx
=> Fix modal scrolling on iOS.

src/components/profile-card.css, src/components/profile-modal.css, src/components/profile-modal.jsx
| Before | After |
|:---:|:---:|
| ![Screen Shot 2020-04-17 at 1 31 41 AM](https://user-images.githubusercontent.com/813865/79487804-5e3a4100-804b-11ea-8e82-7897c4a9660a.png) | ![Screen Shot 2020-04-17 at 1 32 08 AM](https://user-images.githubusercontent.com/813865/79487819-62fef500-804b-11ea-8d1f-54660a841c33.png) |
=> Improvements to modal styling

src/components/profile-card.jsx, src/components/profile-modal.jsx
=> Have conditional rendering for organization

package-lock.json, package.json, src/App.css, src/App.js, src/components/search-bar.jsx, src/mentors.js, src/search.js, src/waves.json
Closes #81.
This PR should probably be merged after #82.
=> Add tabbed pages for each wave.

src/mentors.js
=> Sort mentor IDs by display name alphabetically.

src/App.js
=> Sort waves in descending order.

package.json
This ensures that React will render the pages with the correct root URL.
=> package.json: Update homepage

src/App.js
This PR aims to refactor a couple of hooks within the codebase so as to make the code more idiomatic.
=> Refactor Hooks

src/components/header.jsx
This PR adds a sample application response PDF, shared on Google Drive.
=> Header: Add sample application response

data/profile_images/AlexLoh.jpg, data/profile_images/ChengHuiSng.jpg, data/profile_images/HazelPeh.jpg
This PR contains a few changes to profile pictures that were missed out in the previous PR.
=> Mentors: Hotfix 3.4

src/components/header.jsx
This PR updates the Typeform link to the Wave 3 form.
=> Header: Update Typeform link

data/profile_images/BernardTay.jpg
This PR changes Bernard Tay's profile picture.
=> Mentors: Hotfix 3.7

src/components/header.jsx
This PR adds terms for mentee applications.
=> Header: Add terms for mentee applications

.github/workflows/deploy-gh-pages.yml
=> GitHub Actions: Correct and standardise workflow names

.github/workflows/deploy-lambda.yml, package-lock.json, package.json
See title of PR and https://docs.npmjs.com/cli/v7/configuring-npm/package-lock-json#lockfileversion for more details.
=> package-lock.json: Upgrade lockfile to v2

src/components/profile-card.jsx, src/components/profile-modal.jsx, src/mentors.js
=> Add industry field to mentors

src/App.js
Fixes https://github.com/AdvisorySG/mentorship-page/issues/286.
=> App.js: Add placeholder text

package-lock.json, package.json, src/App.css, src/App.js, src/components/search-bar.css, src/components/search-bar.jsx, src/search.js
Recreated SearchBar using Material-UI and lunr. SearchBar can now be filtered, too.
=> New SearchBar

src/App.js
=> App: Update privacy notice

src/components/header.jsx, src/mentors.js
=> Hotfix: More miscellaneous changes

src/components/header.jsx
=> Header: Add link to FAQ

package-lock.json, package.json, src/components/search-bar.jsx, src/waves.js
https://github.com/AdvisorySG/mentorship-page/issues/335
Industry autocomplete should work successfully.
=> Industry Autocomplete

src/components/header.jsx
=> Updated blurb

package.json, scripts/load_mentors.js, src/interfaces.ts, src/waves.ts
This PR prepares the site for the implementation of Search UI with ElasticSearch. See commit history for more details.
=> Prepare site for Search UI with ElasticSearch

src/App.tsx
=> added role and course of study to filter field

src/components/ResultView.tsx, src/index.css
=> ResultView: Implement coloured industries

src/components/ResultView.css, src/components/ResultView.tsx
Redesign Mentor Card to be more UX-friendly
=> Redesign mentor card to be more UX-friendly

package-lock.json, package.json, src/components/ResultView.css, src/components/ResultView.tsx, src/globals.d.ts
Close #399
Fix style consistency issue and highlighting of search results
=> Add dropdown

src/components/ResultView.css
Fix the image height when viewing on smaller screens
=> Fix height to resolve image overlapping bug

src/components/ResultView.tsx
=> Conditionally render mentor's course of study and school

src/App.tsx
=> Add scrollable tabs

src/components/ResultViewGrid.tsx
Addressing --> Card: Images are not aligned #506
=> fix: image misalignment

package-lock.json, package.json
Elastic Search UI was causing issues in the netlify builds, so for now I rolled it back
=> Rollback elastic search UI

scripts/load_mentors.js
Script updates Airtable images when mentors are updated. Full migration of images has been settled by changing & adding these lines (to reindex all mentors)
```js
/*const indexMentors = [...mentorMap.entries()].filter(
([mentorId, mentor]) => !unmodifiedMentorIds.has(mentorId) && mentor.name
);*/
const indexMentors = [...mentorMap.entries()];
```
Tested the logic and does not seem to be any issues
AWS to be configured with an S3 bucket, and lambda function needs to be given permission to upload files to S3 (not too sure how this will be done)
Code can be tested locally using AWS Access Keys
```js
const s3 = new AWS.S3({
accessKeyId: AWS_S3_ACCESS_KEY_ID,
secretAccessKey: AWS_S3_SECRET_ACCESS_KEY,
});
```
=> Lambda script to migrate Airtable images to AWS & update links

pages/faq.tsx
Followed https://github.com/AdvisorySG/mentorship-page/pull/581#discussion_r1189284733
=> [MPT-24] feat: bold questions

components/Drawer.tsx, package-lock.json, package.json, pages/application.tsx, pages/apply.tsx, pages/faq.tsx, styles/Header.css
For now left the resources as is (couldn't think of a good way to make the links buttons instead)
=> [MPT-26] feat: base structure of application page

pages/faq.tsx
=> [MPT-25] FAQ: Add questions from 2022 Wave 

components/Header.tsx, pages/apply.tsx, pages/faq.tsx, pages/index.tsx, pages/mentors.tsx
=> [MPT-29] feat: header on diff pages

components/Drawer.tsx, components/Header.tsx
Added a home button to the navigation bar that brings the user back to the landing page of the website.
=> [MPT-43] No Home Button

.github/workflows/deploy-lambda.yml, .github/workflows/prettier.yml, package-lock.json, package.json
To resolve https://github.com/AdvisorySG/mentorship-page/issues/646.
=> build: update workflows for node v18

styles/App.css
Recreated to trigger deploy preview
=> [MPT-56] Inserted css for results per page label

components/Footer.tsx
=> [MPT-58] FAQ:Add padding between content and footer

components/Footer.tsx, pages/apply.tsx
I made all pages have the navbar at the same position so that it stops twitching
=> [MPT-59] Twitching menu bar when clicked

pages/mentors/[id].tsx
=> [MPT-85] Mentors: Remove School filter option

pages/faq.tsx
=>  [MPT-33] FAQ: Questions sections hard to see

components/Footer.tsx
Changed the year and charity name at the footer of the webpage
=> For Issue MPT-82

components/Footer.tsx
=> [MPT-107] fixed alignment

components/Drawer.tsx, components/Footer.tsx
=> [MPT-114] Issue 788

styles/ResultView.css
This PR is blocked by PR https://github.com/AdvisorySG/mentorship-page/pull/797 and closes MPT-108 (https://github.com/AdvisorySG/mentorship-page/issues/778) and MPT-103 (https://github.com/AdvisorySG/mentorship-page/issues/770).
=> [MPT-108] [MPT-103] refactor(styles): use grid

src/styles/App.css
Fixes https://github.com/AdvisorySG/mentorship-page/issues/805.
=> [MPT-118] fix(mentors): layer mobile filter sidebar at top

package-lock.json, package.json
=> [MPT-146] bump(deps): update Elastic UI packages to v1.23.0

scripts/load_mentors.js, src/app/mentors/page.tsx
See https://github.com/AdvisorySG/mentorship-page/issues/918. This PR applies a hotfix for Mentorship 2025, but doesn't actually fix the issue.
=> [MPT-150] fix(mentors)!: disable global filter
