AdvisorySG/mentorship-page

src/components/profile-modal.css
src/components/profile-modal.jsx

Also changes the overlay to a semi-transparent dark background.
Here’s a few comparison screenshots:
| | **Before** | **After** |
|---|---|---|
| **Smaller Viewports** | ![Screen Shot 2020-04-16 at 12 42 14 AM](https://user-images.githubusercontent.com/813865/79364320-c7eb1a00-7f7b-11ea-9641-c07c0578047b.png) | ![Screen Shot 2020-04-16 at 12 31 49 AM](https://user-images.githubusercontent.com/813865/79364312-c588c000-7f7b-11ea-890b-fd18fd51edfe.png) |
| **Larger Viewports** | ![Screen Shot 2020-04-16 at 12 41 58 AM](https://user-images.githubusercontent.com/813865/79364317-c6b9ed00-7f7b-11ea-93b4-2ba8ea55b735.png) | ![Screen Shot 2020-04-16 at 12 29 09 AM](https://user-images.githubusercontent.com/813865/79364303-c15ca280-7f7b-11ea-83bf-98f18d79d5c7.png) |
Closes #22.

Simplify CSS for modal and avoid overflow issues.

---

.gitattributes
public/assets/resumeguide.pdf
src/components/header.jsx

This reduces bandwidth usage on GH Pages.

Header: Replace PDF guide for Google Drive

---

src/components/search-bar.jsx

This addresses the previous comment made by @RyanRTJJ that people might think the search bar would search across multiple waves.

SearchBar: Add wave name to placeholder text

---

src/App.js

@wei2912 here's the issue you mentioned. Seems like we've addressed this before, but maybe it got wiped in a merge?

Ensure modal opens on load if there is a URL hash.

---

src/assets/index.js

Previously, the header had missing images:
Inspection showed that the images weren't loaded by `webpack`:
This was due to a change in `file-loader`. For information on the fix, see
https://stackoverflow.com/questions/59070216/webpack-file-loader-outputs-object-module.

Header: Fix missing images

---

scripts/load_mentors.js

This is required for the lambda to function as intended.

load_mentors.js: JSON stringify response body

---

scripts/load_mentors.js

This simplifies the return format of the lambda and follows the guidelines at https://docs.aws.amazon.com/apigateway/latest/developerguide/http-api-develop-integrations-lambda.html#http-api-develop-integrations-lambda.v2. By returning a valid JSON string, API Gateway will infer the remaining parameters.
After this PR, API requests should return the JSON data directly and as `application/json` rather than plain text.

load_mentors.js: Return stringified JSON directly

---

package.json
src/components/profile-card.css
src/components/profile-card.jsx

Fixes https://github.com/AdvisorySG/mentorship-page/issues/282. Should scale nicely to small screens, since the tag is set at 80% of width.

profile-card: Add industry tag

---

src/App.css
src/App.js
src/components/header.jsx

This PR changes the blurb for the Mentorship 2021 wave and repositions the disclaimer to below the separator between the introduction and the mentors canvas..

Rework blurb and disclaimer

---

src/components/search-bar.jsx

Quickfix: Memoize the computed lunr object to avoid re-computing it on every render.

Optimize search bar

---

src/App.css
src/App.js

Set a minimum height of the full screen height to prevent the scroll position from changing when results are filtered out.

Prevent layout shifting when searching

---

scripts/load_mentors.js
src/mentors.js

As discussed, this PR utilises Airtable's record ID as an unique identifier for each mentor. This will prevent issues with mentors having the same names if the order of rows, as returned by Airtable, were to change, since sorting is done by the first name.

Use Airtable's record ID as mentorId

---

src/App.css

Mainly added left and right padding of 16px to privacy statement. In effect regardless of mobile/ desktop view
Before
After

Add padding to privacy statement

---

src/components/ResultView.tsx

This hotfix amends the commit at
https://github.com/AdvisorySG/mentorship-page/commit/e21e5adb6d07c9433c10bd074038048b94f217c9
with a solution as proposed in
https://github.com/AdvisorySG/mentorship-page/commit/08131e50507ba96655c707bb7a1573ac8e855e43,
to handle potential edge cases where non-bracketed characters at the start/end may be
missing.

ResultView: Hotfix for missing brackets in snippets

---

scripts/load_mentors.js

This PR enforces unique industries.
**This code has not been tested. After merging, please wait for the build to finish and then wait an additional 20 minutes for the Elasticsearch data to refresh, then verify that no more duplicate industries exist!**
Sample test cases:

load_mentors: Enforce unique industries

---

scripts/load_mentors.js
src/App.tsx

This PR comprises changes to `load_mentors.js` to upload new waves from Airtable into Elastic Cloud, and also refines the current tab data.

Prepare website for institution-specific wave

---

scripts/load_mentors.js

I modified the code to pick out only the mentors that were modified and index them. This should conserve network bandwidth on reindexing.

Only reindex modified mentors

---

scripts/load_mentors.js

I filtered out Airtable entries which are nameless when updating the ElasticSearch, which should act as a backup method to stop the issue. I also added back the functionality to add new mentors from the Airtable to the ElasticSearch

Filter out nameless entries

---

pages/index.tsx
scripts/load_mentors.js

See title of PR. Mentors will not be visible until this PR is merged and the `load_mentors.js` lambda is executed.

add vjc mentorship 2023 wave

---

pages/_app.tsx

For now using a relative path for ease of development. If we want an absolute path to the image we may need to create configuration variables to reference.
https://vercel.com/docs/concepts/projects/environment-variables
https://github.com/vercel/next.js/discussions/16429

[MPT-28] fix: public_url for logo

---

components/ResultViewGrid.tsx
components/ResultViewList.tsx
pages/index.tsx

The following events are now tracked:
1. `Tab ${tabName}`
2. "Grid view"/"List view"
2. "Read more (grid view)"
3. "Read more (list view)"/"Read less (list view)"
Closes https://github.com/AdvisorySG/mentorship-page/issues/607.

[MPT-27] umami: add tracking events

---

components/ResultViewGrid.tsx
styles/ResultView.css
styles/ResultView.module.css

fixed formatting issue where the 1st mentor card in the grid format is misaligned with the other mentor card

[MPT-32] mentors: fix formatting #606 

---

pages/mentors.tsx

I first revert to multi-tab by doing the following
```javascript
const WAVES = [
{ waveId: 4, waveName: "VJC Mentorship 2023" },
{ waveId: 5, waveName: "Wave 2023" },
];
```
Then I noticed that the search result reset to the first page with you click the search button which has the class name `button sui-search-box__submit`
Therefore, I identified the element and simulated a click after the tab switch as shown
```javascript
const handleTabChange = (_: React.ChangeEvent<{}>, tab: number) => {
setCurrentTabId(tab);
const button = document.querySelector(
'input[class="button sui-search-box__submit"]'
) as HTMLButtonElement;
if (button) {
button.click();
}
};
```

fix: attempt to fix issue #519 MPT-14 through clicking the search button

---

components/ResultViewGrid.tsx

The `max-width` attribute is still set to 165px, so there should be no awkward sizing issues. 
Before:
After:

Add a width attribute to the Card component and set it to 100%

---

components/ResetButton.tsx
pages/mentors/[id].tsx

This pull request introduces a new "Clear Filters" button that allows users to easily reset all applied filters on the page. It is to address issue [\[MPT-70\]](https://github.com/AdvisorySG/mentorship-page/issues/723)
A new component called `ResetButton.tsx` was created to handle the clearing functionality.
The button utilizes the existing `removeFilter` function to clear individual filters.
The component has a function that loops through the `filter` and clears them individually.
```
const handleClearAll = () => {
for (const filter of filters) {
removeFilter(filter.field, filter.value);
}
};
```
- https://discuss.elastic.co/t/selectedfilter-resetsearchbutton/275284

[MPT-70] New clear filter button

---

pages/index.tsx

I modified the margin-left and margin-right of the arrows such that they make use of a percentage value for the margin instead of a fix value of 0 and 300px. This prevents the carousel arrows to be flipped on narrow displays.

[MPT-66] Home: Carousel arrows are flipped on narrow displays

---

components/ResultViewGrid.tsx
styles/App.css
styles/ResultView.css

Old implementation:
New implementation:
This additional change was requested by Wei En

[MPT-68] Search bar is narrow on mobile phone 

---

pages/index.tsx

Initial Issue - Mobile view/ other view bugs out
Suspected root cause of the issue is the `isSmall` variable
```
const Index = () => {
const isSmall = useMediaQuery("(max-width: 800px)");
const glideRef = useRef(null);
```
When the component is first initialised, the value is ALWAYS false, regardless of orientation. It is then rendered once. This variable is then updated, but the component is not rerendered/ reinitialised after the variable update. The buggy mentor/ mentee listing (and hence offset) would then appear.
The PR initialises the Carousel only AFTER the media query is properly updated (a timeout is a simple enough fix, `useEffect` might be too complicated and interfere with the React Lifecycle). The component would then be rendered with the proper props & styling
Can compare …

[MPT-110] Fix Testimonial Carousel

---

components/ResultView.tsx
components/ResultViewGrid.tsx
package-lock.json
package.json

Due to changes in React 18, under Strict Mode, useEffect will be triggered twice upon render.
It is recommended to not override this behaviour, and to instead specify information distinguishing between development and production environment. See https://react.dev/learn/synchronizing-with-effects#sending-analytics for more details.
Closes https://github.com/AdvisorySG/mentorship-page/issues/799.

[MPT-116] feat(umami): record document ID + process env in impression/click

---

src/styles/Header.css

[MPT-111] fix logo stretching too wide on mobile
